export const badges = [{
    title: 'Welcome cupcake!',
    description: 'Welcome, maker! Here’s a cupcake.',
    criteria: 'Sign-up to Kano',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/welcome-cupcake.svg',
    id: 'welcome-cupcake',
    unlocked: true,
    date: '2017-05-08T14:17:44.553Z',
}, {
    title: 'Challenger',
    description: 'High-Five🖐 You’ve completed your first challenge!',
    criteria: 'Complete 1 challenge',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/challenger.svg',
    id: 'challenger',
    unlocked: true,
    date: '2017-06-13T10:06:32.819Z',
}, {
    title: 'Champion',
    description: 'You’ve completed 10 challenges! 👊',
    criteria: 'Complete 10 challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/champion.svg',
    id: 'champion',
    unlocked: true,
    date: '2017-06-23T13:02:33.688Z',
}, {
    title: 'Conqueror',
    description: '30 Challenges done. You’re becoming a Kano Master!',
    criteria: 'Complete 30 challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/conqueror.svg',
    id: 'conqueror',
    unlocked: false,
}, {
    title: 'Double Day Daredevil',
    description: '🔥 You’re on a 2 day streak! 🔥',
    criteria: 'Return 2 days in a row',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/sassy-streaker.svg',
    id: 'double-day-daredevil',
    unlocked: true,
    date: '2017-07-21T10:19:56.215Z',
}, {
    title: 'Weekly Winner',
    description: '🔥 You’re on a week-long streak! 🔥',
    criteria: 'Return 7 days in a row',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/weekly-winner.svg',
    id: 'weekly-winner',
    unlocked: true,
    date: '2017-08-01T11:07:04.837Z',
}, {
    title: 'Committed Coder',
    description: '🔥 You’re on a 2 week streak! 🔥',
    criteria: 'Return 14 days in a row',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/committed-coder.svg',
    id: 'committed-coder',
    unlocked: true,
    date: '2017-08-21T14:06:28.143Z',
}, {
    title: 'Monthly Master',
    description: '🔥 You’re on a month-long streak! 🔥',
    criteria: 'Return 30 days in a row',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/monthly-master.svg',
    id: 'monthly-master',
    unlocked: true,
    date: '2017-08-21T14:07:16.941Z',
}, {
    title: 'Heartfelt Hero',
    description: 'You’ve been friendly and liked 10 creations!',
    criteria: ' Like 10 creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/heartfelt-hero.svg',
    id: 'heartfelt-hero',
    unlocked: true,
    date: '2017-05-25T16:51:27.054Z',
}, {
    title: 'Big-heart Boss',
    description: 'This is your 30th like! You’re so nice.',
    criteria: 'Like 30 creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/big-heart-boss.svg',
    id: 'big-heart-boss',
    unlocked: true,
    date: '2017-05-26T10:53:53.699Z',
}, {
    title: 'Sparkly Sharer',
    description: 'You’ve shared your first creation!',
    criteria: 'Share 1 creation',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/sparkly-sharer.svg',
    id: 'sparkly-sharer',
    unlocked: false,
}, {
    title: 'Sharer Supreme',
    description: 'You’ve shared 10 creations!',
    criteria: 'Share 10 creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/sharer-supreme.svg',
    id: 'sharer-supreme',
    unlocked: true,
    date: '2017-07-24T10:59:00.120Z',
}, {
    title: 'Clingy Cactus',
    description: 'You’re following 5 Kanoers!',
    criteria: 'Follow 5 users',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/clingy-cactus.svg',
    id: 'clingy-cactus',
    unlocked: true,
    date: '2017-06-26T11:49:16.200Z',
}, {
    title: 'Remix Rookie',
    description: 'You’ve remixed someone else’s code and made it your own!',
    criteria: 'Remix 1 creation',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/remix-rookie.svg',
    id: 'remix-rookie',
    unlocked: false,
}, {
    title: 'Remix Ruler',
    description: 'Awesome… You’ve remixed 10 creations!',
    criteria: 'Remix 10 creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/remix-ruler.svg',
    id: 'remix-ruler',
    unlocked: false,
}, {
    title: 'Inspiring Inventor',
    description: 'Cool! One of your creations was remixed!',
    criteria: 'Your creation is remixed',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/inspiring-inventor.svg',
    id: 'inspiring-inventor',
    unlocked: false,
}, {
    title: 'Super Streaker',
    description: '⚡️ Woah! You’ve done 1 challenge every day for 7 days in a row! ⚡️',
    criteria: 'Complete 1 challenge every day for 7 days in a row',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/super-streaker.svg',
    id: 'super-streaker',
    unlocked: false,
}, {
    title: 'Smashing Streaker',
    description: '🌟 Amazing! You’ve completed 1 challenge a day for 14 days in a row! 🌟',
    criteria: 'Complete 1 challenge every day for 2 weeks',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/smashing-streaker.svg',
    id: 'smashing-streaker',
    unlocked: false,
}, {
    title: 'Pixel Pioneer',
    description: 'You’ve completed 5 light challenges!',
    criteria: 'Complete 5 pixel challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-pioneer.svg',
    id: 'pixel-pioneer',
    unlocked: false,
}, {
    title: 'Pixel Paragon',
    description: 'You’ve completed 10 light challenges!',
    criteria: 'Complete 10 pixel challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-paragon.svg',
    id: 'pixel-paragon',
    unlocked: false,
}, {
    title: 'Pixel Intro',
    description: 'Awesome! You’ve finished the intro challenges!',
    criteria: 'Complete the pixel intro challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-intro.svg',
    id: 'pixel_intro',
    unlocked: true,
    date: '2017-06-30T14:39:20.832Z',
}, {
    title: 'Pixel Mic',
    description: 'You’ve made lights and sounds play together!',
    criteria: 'Complete the pixel mic challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-mic.svg',
    id: 'pixel_mic',
    unlocked: false,
}, {
    title: 'Pixel Dot Eater',
    description: 'You just made a game, from scratch!',
    criteria: 'Complete the pixel dot eater challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-dot-eater.svg',
    id: 'pixel_dot_eater',
    unlocked: false,
}, {
    title: 'Pixel Rainbow',
    description: 'You’ve made rainbows shine!',
    criteria: 'Complete the pixel rainbow challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-rainbow.svg',
    id: 'pixel_rainbow',
    unlocked: false,
}, {
    title: 'Pixel Action Painting',
    description: 'You’ve been painting with light!',
    criteria: 'Complete pixel action painting challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/pixel-action-painting.svg',
    id: 'pixel_action_painting',
    unlocked: false,
}, {
    title: 'Powerful Painter',
    description: 'You’ve completed 5 drawing challenges!',
    criteria: 'Make 5 Kano Code animation creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/powerful-painter.png',
    id: 'powerful-painter',
    unlocked: false,
}, {
    title: 'Awesome Artist',
    description: 'You’ve completed 10 drawing challenges!',
    criteria: 'Make 10 Kano Code animation creations',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/awesome-artist.png',
    id: 'awesome-artist',
    unlocked: false,
}, {
    title: 'Motion Intro',
    description: 'Awesome! You’ve finished the intro challenges!',
    criteria: 'Complete the motion intro challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/motion-intro.svg',
    id: 'motion_intro',
    unlocked: false,
}, {
    title: 'Motion Swiper',
    description: 'Keep swiping!',
    criteria: 'Complete the motion swipe challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/motion-gesture.svg',
    id: 'motion_gesture',
    unlocked: false,
}, {
    title: 'Motion Guitarist',
    description: 'Playing the guitar like a pro!',
    criteria: 'Complete the motion guitar challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/motion-guitar.svg',
    id: 'motion_guitar',
    unlocked: false,
}, {
    title: 'Motion Pong Master',
    description: 'You just made pong, from scratch!',
    criteria: 'Complete the motion pong challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/motion-pong.svg',
    id: 'motion_pong',
    unlocked: false,
}, {
    title: 'Motion LERP',
    description: 'Lerp, lerp, lerp!',
    criteria: 'Complete the motion lerp challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/motion-lerp.svg',
    id: 'motion_lerp',
    unlocked: false,
}, {
    title: 'Snappy Snapper',
    description: 'You’ve completed 5 photography challenges!',
    criteria: 'Complete 5 photography challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/snappy-snapper.svg',
    id: 'snappy-snapper',
    unlocked: false,
}, {
    title: 'Sir Snaps-a-lot',
    description: 'You’ve completed 10 photography challenges!',
    criteria: 'Complete 10 photography challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/sir-snaps.svg',
    id: 'sir-snaps-a-lot',
    unlocked: false,
}, {
    title: 'Soulful Soundmaker',
    description: '5 sound challenges completed. Well done!',
    criteria: 'Complete 5 sound challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/soulful-soundmaker.svg',
    id: 'soulful-soundmaker',
    unlocked: false,
}, {
    title: 'Brilliant Beatmaker',
    description: 'You’ve completed 10 sound challenges!',
    criteria: 'Complete 10 sound challenges',
    imageUrl: 'https://s3-eu-west-1.amazonaws.com/world.kano.me.staging/static/gamification/badges/brilliant-beatmaker.svg',
    id: 'brilliant-beatmaker',
    unlocked: false,
}];
